coaster/logging.py
SMSs are sent to a defined list of numbers when a log with level ERROR occurs (Similar to the SMTP system currently in place)
SMSs are throttled based on the following rules
* SMSes aren't sent if an error had occurred in the last 5 minutes.
```python
ADMIN_NUMBERS = []
SMS_EXOTEL_SID = ''
SMS_EXOTEL_TOKEN = ''
SMS_EXOTEL_FROM = ''
SMS_TWILIO_SID = ''
SMS_TWILIO_TOKEN = ''
SMS_TWILIO_FROM = ''
```
=> SMS Notifications for errors

tests/test_app.py
Remove the unused import - configure
Remove configure from TestCoasterUtils, use init_app() instead
Rename coaster.logger's init_app to logger_init_app
=> Remove deprecated configure()

CHANGES.rst, coaster/sqlalchemy.py, setup.py
Mark Query class's one_or_none() deprecated in favor of using
SQL-Alchemy's native one_or_none.
=> Fix issue #66

coaster/views.py
Usage:
```python
from flask import Response
import app
def check_origin(origin):
return True
@app.route('/')
@cors(check_origin)
def index():
return Response()
````
=> Adds a `cors` decorator to manage cross-origin requests

CHANGES.rst, coaster/roles.py, coaster/sqlalchemy.py, tests/test_roles.py
Fixes #139 and addresses the concerns raised in #138.
=> Rename set_roles to with_roles and add support for declared_attr and column properties

coaster/sqlalchemy/statemanager.py, tests/test_statemanager.py
These commits introduce a breaking change, but in unused functionality. There is also a contestable choice in using `bestmatch()` for `state.label`. This suits a current requirement in Funnel, but may be a problem elsewhere, and will therefore need revisiting.
For code review, please look at each commit separately. It will be easier to understand.
=> StateManager updates (resolves #165)

CHANGES.rst, coaster/utils/classes.py, coaster/views/classview.py, tests/test_views_classview.py
Breaking change since before_request no longer gets the ‘view’
parameter. If needed, it can consult self.current_handler instead.
=> ClassView fixes and improvements

coaster/gfm.py
Markdown library has removed `safe_mode` from `Markdown()` in version 3.0 and recommends using 3rd party library like Bleach for cleaning strings. Or using extensions to achieve `safe_mode=escape`.
Ref: https://github.com/Python-Markdown/markdown/blob/f51125d01b88067d8523e9706cfa4558b3808222/docs/change_log/release-3.0.md#safe_mode-and-html_replacement_text-keywords-deprecated
=> Removed deprecated safe_mode from Markdown()

CHANGES.rst, coaster/sqlalchemy/mixins.py, coaster/views/classview.py, tests/test_models.py, tests/test_url_for.py
Also deprecate silent failure during a build error.
=> Support multiple apps in UrlForMixin. Resolves #199, #9

coaster/views/classview.py, tests/test_views_classview.py
InstanceLoader does double duty: loading an instance based on query parameters, and checking permissions for the given view. Any view with a non-trivial URL will provide its own loader, skipping InstanceLoader. Unfortunately this means the permission management code needs to be reproduced in each view class.
By moving the relevant code to ModelView, we remove this duplication. Here's an example of the unnecessary duplication that appears multiple times in this file:
https://github.com/hasgeek/lastuser/blob/a31ff8798e88121d1616e337dbedbb7939ffb759/lastuser_ui/views/org.py#L31-L34
=> Move permission management from InstanceLoader to ModelView; fix joins

coaster/sqlalchemy/mixins.py, coaster/views/classview.py, tests/test_url_for.py, tests/test_views_classview.py
This PR closes the functionality gap between `load_models` and `ModelView`. In cases where the child has no backref to its parent, the parent is responsible for generating URLs to the child, and will expect to receive the child as a parameter to `url_for`.
=> Support for multiple models in url_for and ModelView. Resolves #208

CHANGES.rst, coaster/sqlalchemy/__init__.py, coaster/sqlalchemy/mixins.py, coaster/sqlalchemy/registry.py, coaster/views/classview.py, docs/sqlalchemy/index.rst, docs/sqlalchemy/registry.rst, tests/test_sqlalchemy_registry.py, tests/test_views_classview.py
This PR makes it possible for forms and views to be registered to a model, and accessed from the model later. A ModelView subclass (or a Form) can be registered to a model like this:
```python
MyModel.views.main = MyView
```
It can be subsequently accessed from an instance of the model:
```python
model_instance.views.main() == MyView(obj=model_instance)
```
A view constructed like this is similar to one constructed via a request, except:
1. The `obj` parameter is passed to `__init__`, which (in `ModelView.__init__`) saves it to `self.obj`.
2. The setup methods `loader` and `after_loader` and request handler methods `before_request` and `after_request` are not called.
There are two pending issues that may not be serious:
1. In multi-model views, `loader` may return a `tuple`, which is …
=> Model helper registry. Resolves #207

coaster/sqlalchemy/columns.py, setup.py, tests/test_models.py
This `UrlType` is based on [`URLType` from SQLAlchemy-Utils](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.url). Except it takes a `schemes` param.
=> Added UrlType

coaster/db.py, setup.py, test_requirements.txt
PostgreSQL and SQLAlchemy exhibit timezone calculation errors when using naive timestamps and non-UTC timezones. This patch tells PostgreSQL to always use UTC.
=> Always use UTC timezone with PostgreSQL

coaster/sqlalchemy/roles.py, tests/test_roles.py
Tests pending. Also investigating the possibility of extending this to list and query (lazy) relationships.
=> Role access for scalar and collection relationships (for #220)

CHANGES.rst, coaster/auth.py, coaster/sqlalchemy/roles.py, coaster/utils/classes.py, coaster/utils/misc.py, setup.cfg, tests/test_auth.py, tests/test_roles.py, tests/test_utils.py
This PR removes the need for models to provide `roles_for` methods. Instead, roles are discovered automatically from relationships as declared in `__roles__` so:
```python
__roles__ = {
'owner': {
'granted_by': ['user', 'admins'],
},
}
```
Calling `obj.roles_for(user)` will now return a `LazyRoleSet` which initially does not contain any roles (other than the standard set of `all` and `auth` or `anon`). A test such as `'owner' in obj.roles_for(current_auth.user)` or `obj.current_roles.owner` will trigger the actual lookup, wherein the lazy role set will evaluate if the given actor is present in the object's `user` and `admins` attributes, in order (from the example above).
Scalar, collection-type and query-type (dynamic) relationships are all supported, but not dict-type relationships, as …
=> LazyRoleSet, role grants, and initial tests

coaster/sqlalchemy/mixins.py, tests/test_sqlalchemy_coordinates.py
The `has_coordinates` property makes it easier to verify if a location has coordinates for displaying on a map.
=> Data verification properties for CoordinatesMixin

coaster/app.py, setup.py, tests/test_app.py
Flask sets production as the default environment. Coaster should also do so.
=> production should be the default environment

coaster/utils/datetime.py, setup.py, tests/test_utils.py
YouTube's API returns video duration in ISO8601 format: https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm
Hence adding the parser for it in coaster
=> Replaced old iso8601 lib with aniso8601

coaster/sqlalchemy/mixins.py, tests/test_sqlalchemy_models.py
Needs to be a property for casting into JSON via RoleAccessProxy. This is a breaking change requiring updates in all apps that use short_title
=> Turn short_title into a property

CHANGES.rst, coaster/sqlalchemy/annotations.py, coaster/sqlalchemy/immutable_annotation.py, coaster/sqlalchemy/roles.py, tests/test_sqlalchemy_annotations.py, tests/test_sqlalchemy_models.py, tests/test_sqlalchemy_roles.py
Annotations and roles can no longer be defined on synonyms. However, synonyms appear in role access under the original attribute's access levels, to support downstream usage under the synonym name.
=> Support SQLAlchemy 1.4, with a compromise

.travis.yml, coaster/app.py, coaster/manage.py, coaster/sqlalchemy/statemanager.py, setup.py
Removed in pallets/flask#3895, and we were not using it anyway. `SandboxedFlask` was only used in Eventframe (introduced 2012, discontinued 2017-18, shutdown 2020).
=> Partial Flask 2.0 compatibility

coaster/views/misc.py
The use of else or elif becomes redundant and can be dropped if the last statement under the leading if / elif block is a return statement.
=> Unnecessary `else` / `elif` used after `return`

.github/workflows/pytest.yml, .github/workflows/telegram.yml, .gitignore, .pre-commit-config.yaml, CHANGES.rst, coaster/app.py, coaster/auth.py, coaster/db.py, coaster/sqlalchemy/annotations.py, coaster/sqlalchemy/roles.py, coaster/sqlalchemy/statemanager.py, coaster/utils/misc.py, coaster/views/classview.py, coaster/views/decorators.py, setup.py, test_requirements.txt, tests/settings.py, tests/test_app.py, tests/test_auth.py, tests/test_sqlalchemy_annotations.py, tests/test_sqlalchemy_coordinates.py, tests/test_sqlalchemy_markdowncolumn.py, tests/test_sqlalchemy_models.py, tests/test_sqlalchemy_registry.py, tests/test_sqlalchemy_roles.py, tests/test_url_for.py, tests/test_views_classview.py, tests/test_views_loadmodels.py
The `request_has_auth` helper function accompanying `current_auth` is meant to be used in an after_request processor to set a `Vary: Cookie` header if the request accessed `current_auth` in any way, implying that it is auth-sensitive. Unfortunately, since the `current_auth` proxy is included in the Jinja2 environment, this means any rendering of a template will invoke current_auth, even if the template does not need it.
This PR changes `current_auth` to only initialize itself when the `actor` or `user` properties are read, thereby removing the Jinja2 issue.
Potential problem: if a view or template does access `current_auth`, but in the very first access attempts to read another variable that was expected to be set by the login manager, it will not exist as the login manager will only be …
=> Improved current_auth and other fixes

.pre-commit-config.yaml, pyproject.toml, src/coaster/db.py, src/coaster/sqlalchemy/columns.py, src/coaster/sqlalchemy/comparators.py, src/coaster/sqlalchemy/mixins.py, src/coaster/utils/misc.py, tests/conftest.py, tests/test_auth.py, tests/test_sqlalchemy_annotations.py, tests/test_sqlalchemy_coordinates.py, tests/test_sqlalchemy_markdowncolumn.py, tests/test_sqlalchemy_models.py, tests/test_sqlalchemy_registry.py, tests/test_sqlalchemy_roles.py, tests/test_statemanager.py, tests/test_url_for.py, tests/test_views_classview.py, tests/test_views_loadmodels.py
UUIDType has been a recurring source of pain as SQLAlchemy doesn't understand the type (and queries are broken in SQLAlchemy 2.0.x), so we're dropping it to commit to SQLAlchemy's own PostgreSQL-only UUID column. This means the SQLite tests are no longer usable and have to be removed.
=> Drop use of UUIDType from SQLAlchemy-Utils, and drop SQLite tests

src/coaster/sqlalchemy/roles.py, tests/coaster_tests/sqlalchemy_roles_test.py
RoleAccessProxy now supports equality tests with the wrapped object, so client code can use `proxy<obj> == obj`.
=> Make RoleAccessProxy transparent

src/coaster/app.py, tests/coaster_tests/app_test.py, tests/coaster_tests/sqlalchemy_modelbase_test.py
Requirement originally in https://github.com/hasgeek/funnel/issues/1729
Also fix possibly unbound var in KeyRotationWrapper.
=> Support config from multiple env prefixes

CHANGES.rst, pyproject.toml, setup.cfg, src/coaster/assets.py, tests/coaster_tests/assets_test.py, tests/coaster_tests/test-manifest.json
The WebpackManifest extension loads a Webpack `manifest.json` file from the app's static folder and makes itself available under the `manifest` name to Jinja2 templates.
Some decisions in this first cut are questionable and may need revision:
1. The default search paths are `static/manifest.json` and `static/build/manifest.json`. The `build` subfolder is a convention in Hasgeek apps but not a Flask convention. Should the `search_paths` parameter be discarded in favour of a simple `path`, defaulting to only `static/manifest.json`?
2. Dictionary access in the form `manifest['asset-name.ext']` will return a default value of `data:,` instead of raising KeyError, making this behaviour different from a regular dict and a bit like using `defaultdict(lambda: 'data:,')`. Call access simply proxies …
=> WebpackManifest Flask extension for Webpack assets in Jinja2 templates

src/coaster/sqlalchemy/roles.py, tests/coaster_tests/sqlalchemy_roles_test.py
To aid static type analysis, `DynamicAssociationProxy` is now a generic that accepts the type of the target attribute.
=> Specify target attribute type in DynamicAssociationProxy

docs/conf.py, src/coaster/app.py, src/coaster/auth.py, src/coaster/db.py, src/coaster/logger.py, src/coaster/sqlalchemy/functions.py, src/coaster/sqlalchemy/markdown.py, src/coaster/sqlalchemy/mixins.py, src/coaster/sqlalchemy/model.py, src/coaster/sqlalchemy/registry.py, src/coaster/sqlalchemy/roles.py, src/coaster/sqlalchemy/statemanager.py, src/coaster/typing.py, src/coaster/utils/misc.py, src/coaster/views/classview.py, src/coaster/views/decorators.py, src/coaster/views/misc.py, tests/coaster_tests/auth_test.py, tests/coaster_tests/sqlalchemy_annotations_test.py, tests/coaster_tests/sqlalchemy_models_test.py, tests/coaster_tests/sqlalchemy_registry_test.py, tests/coaster_tests/sqlalchemy_roles_test.py, tests/coaster_tests/utils_test.py, tests/coaster_tests/views_classview_test.py
ClassView still contained some legacy architecture from the Python 2.7 era. These upgrades use 3.x idioms and add or fix type hinting support.
Unrelated fixes in other modules were noticed when working on ClassView.
=> Modernize ClassView and ModelView

.editorconfig, .gitignore, .pre-commit-config.yaml, pyproject.toml, readthedocs.yml, src/coaster/app.py, src/coaster/auth.py, src/coaster/sqlalchemy/mixins.py, src/coaster/sqlalchemy/model.py, src/coaster/sqlalchemy/roles.py, src/coaster/sqlalchemy/statemanager.py, src/coaster/utils/markdown.py, tests/coaster_tests/auth_test.py, tests/coaster_tests/conftest.py, tests/coaster_tests/sqlalchemy_annotations_test.py, tests/coaster_tests/sqlalchemy_models_test.py, tests/coaster_tests/statemanager_test.py, tests/coaster_tests/url_for_test.py, tests/coaster_tests/views_classview_test.py, tests/coaster_tests/views_endpointfor_test.py
* `current_auth` is now intended to be subclassed by apps so they can specify types for the `actor` and `user` attributes.
* `StateManager` now accepts an Enum instead of a LabeledEnum (partially).
* `RoleMixin` is now a generic on the actor type. Unfortunately this interferes with `IdMixin`'s generic arg, so any class that specifies `UUID` pkey type must also explicitly list the actor type, and conversely when specifying the actor on a table with an int pkey, `int` must be explicitly specified. Where both are unspecified, it defaults to `int` pkey and `Any` actor:
* `BaseMixin` is the same as `BaseMixin[int, Any]`.
* `BaseMixin[UUID]` is now an error as the second arg is missing. [PEP 696](https://peps.python.org/pep-0696/) explicitly allows this, but the PEP is a draft and …
=> Improve typing coverage

.pre-commit-config.yaml, src/coaster/app.py, src/coaster/assets.py, src/coaster/logger.py, src/coaster/sqlalchemy/registry.py
~~Defer locking to the GIL instead (borrowing from the change to `functools.cached_property` in Python 3.12). Also,~~ Avoid `datetime.utcnow()` and use a final class as a sentinel singleton.
=> Minor cleanup
