hasgeek/coaster

coaster/utils.py, docs_requirements.txt, tests/test_utils.py
- optionally converts links to a plain text format i.e text - link.
=> added method that converts html to markdown

docs_requirements.txt, setup.py
Moved dependencies from docs_requirements.txt to setup.py
=> added dependencies to setup.py

CHANGES.rst, coaster/db.py, docs/db.rst, test_requirements.txt, tests/test_models.py
Add and commit automatically rolls back if the commit failed, returning the instance present in the database instead.
=> Provide an add_and_commit method in the session

CHANGES.rst, coaster/sqlalchemy.py, setup.py, tests/test_models.py
Additional tests pending for foreign key references to a table using UUIDs
=> Support UUID primary keys in IdMixin

tests/settings.py, tests/test_manage.py, tests/test_models.py
Changed SQLALCHEMY_DATABASE_URI from IP based to domain socket based
=> changed sqlalchemy_db_uri

setup.py
https://github.com/mozilla/bleach/issues/212
=> bleach breaks with newer versions of html5lib

coaster/sqlalchemy.py
Since `!=` is widely supported but `<>` is the official ANSI operator. Makes no difference to existing code using Coaster. See http://stackoverflow.com/a/723426/78903 for details.
=> Change != to <> SQL operator

coaster/sqlalchemy.py, tests/test_models.py
Addresses https://github.com/hasgeek/coaster/issues/109
=> Added RolesMixin and AccessibleProxy for role-based access control

coaster/sqlalchemy/statemanager.py, tests/test_statemanager.py
Breaking change, since `state.transitions` is no longer a property.
=> StateManager.transitions now coordinates with RoleMixin

.gitignore, coaster/sqlalchemy/statemanager.py, tests/test_statemanager.py
=> Added ability to abort transition

CHANGES.rst, coaster/views/misc.py, setup.py, tests/test_views.py, tests/test_views_endpointfor.py
DO NOT MERGE! Subdomain support is broken at this time.
=> endpoint_for given a URL (subdomain support broken)

CHANGES.rst, coaster/sqlalchemy/mixins.py, tests/test_models.py, tests/test_roles.py
Also drop missing suuid fix for url_name_suuid
=> Rename UuidMixin.url_id to huuid. Fixes #197

coaster/views/classview.py, tests/test_views_classview.py
This is backward-incompatible as it changes the parameters to `before_request` and `loader` in existing implementations.
=> Give view classes better control of flow

coaster/sqlalchemy/mixins.py, coaster/views/classview.py
Existing tests pass. If there is breakage outside test coverage, we should fix that separately.
=> current_permissions inherits from existing permissions. Fixes #211

coaster/sqlalchemy/mixins.py, tests/test_models.py
1. `make_name` now consults `self.title_for_name` instead of `self.title` or `self.short_title()`. Subclasses can override this property to customise name generation. This is expected to be used in Funnel's Label model so that label options can include the main label's title in their name. For eg, `<Label "Session type/Workshop">` has a title of only "Workshop" but can have the name `session-type-workshop` to avoid conflicting with a "Workshop" option in another label.
2. Both `name` and `title` can be `UnicodeText` (unlimited length) instead of `Unicode(length)` if this suits the subclass.
Tests are pending.
=> Add title_for_name and support unlimited length in name/title

README.rst
Hey, DeepSource Dev here.
We recently released a new Badge for GitHub repos, and was wondering if you folks would be interested :-)
=> Add DeepSource Sticker

coaster/sqlalchemy/mixins.py
=> Always pass a set to `.permissions`

coaster/sqlalchemy/roles.py, tests/test_sqlalchemy_roles.py
This is a breaking change and requires a corresponding update in Funnel
=> Offered roles should be a property as it's immutable

coaster/views/classview.py, tests/test_views_classview.py
Don't redirect under conditions that aren't actually different URLs
=> Smarter redirect in url_change_check

coaster/sqlalchemy/roles.py, tests/test_sqlalchemy_roles.py
Adds support for reliable user discovery given a role on an object. Also expands role remapping support to allow 1:n remapping. For example, in Funnel's Proposal model (this is somewhat contrived):
```python
class Proposal:
project = with_roles(
db.relationship(Project),
grants_via={None: {'editor': {'project_editor', 'project_crew'}}}
)
```
... remaps 'editor' on Project to both 'project_editor' and 'project_crew' on Proposal. Before, this only 1:1 remapping was possible and would have been declared as `{'editor': 'project_editor'}`. The old syntax remains valid.
=> Comprehensive `actors_with` implementation and 1:n role remapping

coaster/sqlalchemy/columns.py
Expanding the UrlType from SQLAlchemy-utils - https://github.com/kvesteri/sqlalchemy-utils/blob/989d12a3a39a78d09ce31cde85251eb990bc1442/sqlalchemy_utils/types/url.py
=> Expanding UrlType to use custom furl parser

src/coaster/sqlalchemy/columns.py, tests/coaster_tests/sqlalchemy_models_test.py
There's untested behaviour that's showing up in how Hasjob uses JsonDict.
=> Attempt to parse string values as JSON

pyproject.toml, src/coaster/assets.py, src/coaster/logger.py, src/coaster/sqlalchemy/mixins.py, src/coaster/utils/classes.py, src/coaster/views/classview.py, tests/coaster_tests/sqlalchemy_models_test.py
=> Add default formatter for mixins with title column

setup.cfg, src/coaster/app.py, src/coaster/sqlalchemy/roles.py
Also docstrings and linter tweaks.
=> Better error message in RoleAccessProxy

.pre-commit-config.yaml, src/coaster/sqlalchemy/functions.py, src/coaster/sqlalchemy/roles.py, tests/coaster_tests/sqlalchemy_roles_test.py
Test coverage is indirectly via role tests. Direct test pending.
=> Performance improvements in role access

src/coaster/sqlalchemy/roles.py
* Perf: `LazyRoleSet.__bool__` more performant
* Bugfix: `RoleAccessProxy.__attr_available` accidentally forced enumeration of all roles
* Bugfix: `RoleAccessProxy`'s getitem/setitem/getattr/setattr also accidentally forced enumeration of all roles when raising an exception
=> Lazy role lookup performance optimizations

pyproject.toml, src/coaster/app.py, src/coaster/logger.py, src/coaster/sqlalchemy/columns.py, src/coaster/sqlalchemy/comparators.py, src/coaster/sqlalchemy/functions.py, src/coaster/sqlalchemy/mixins.py, src/coaster/sqlalchemy/model.py, src/coaster/sqlalchemy/registry.py, src/coaster/sqlalchemy/roles.py, src/coaster/sqlalchemy/statemanager.py, src/coaster/utils/classes.py, src/coaster/views/classview.py, src/coaster/views/decorators.py, src/coaster/views/misc.py, tests/coaster_tests/sqlalchemy_roles_test.py
StateManager is now a generic that applies the host's type to conditional lambda functions.
=> Additional typing and related minor fixes

src/coaster/sqlalchemy/roles.py
#451 introduced a bug when it removed the `actor is not None` check for one use case, missing that it was still needed for other checks.
=> Bugfix: only allow actor to be None when scanning a RoleMixin obj

src/coaster/sqlalchemy/roles.py, tests/coaster_tests/sqlalchemy_roles_test.py
This adds an extra generic arg, requiring a typing args change wherever the proxy is used.
=> Expand DynamicAssociationProxy to a Mapping

src/coaster/auth.py, src/coaster/sqlalchemy/markdown.py, src/coaster/sqlalchemy/roles.py, src/coaster/typing.py, src/coaster/views/classview.py, src/coaster/views/decorators.py, tests/coaster_tests/sqlalchemy_annotations_test.py, tests/coaster_tests/views_classview_test.py, tests/coaster_tests/views_renderwith_test.py, tests/coaster_tests/views_test.py
Solution found at https://github.com/python/typing/discussions/1040. Passes type checking in both Mypy and Pyright.
=> Fix decorator typing
